download_directory: tmp/spec/cache
download_bytes: 2M
error_directory: tmp/spec/error
render_directory: tmp/spec/temporary
render_save: true
log_directory: tmp/spec/moviemasher
log_level: debug
s3_read_at_once: true
